version: '3.9'

services:
  api:
    build:
      context: ./infra
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
      # - ./backend/:/backend/
      # - /var/run/docker.sock:/var/run/docker.sock
    # command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port ${API_PORT}
    ports:
      - ${API_HOST_PORT}:${API_PORT}
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    container_name: db
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    tty: true
    restart: always
    user: root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - ${PGWEB_HOST_PORT}:${PGWEB_PORT}
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
